# themeNoPipe: true
title: 냉전아시아 영상아카이브
description: 동아시아 및 한국의 전쟁･냉전, 평화, 일제의 식민지배 피해 및 일본군 ‘위안부’ 문제 관련 자료 조사와 연구, 교육 등의 활동을 통해 학문 발전에 이바지하는 것을 설립 목적으로 하며, (탈)냉전 평화 연구의 거점 싱크탱크, 아시아 최고 수준의 냉전 평화 아카이브, (탈)냉전 평화 교육, 정책 개발, 교류 협력의 허브를 구축하는 비전을 갖고 있습니다. 냉전아시아영상아카이브에 오신 것을 환영합니다.
images:

logo: 
footerLogo: 
header:
  bg: bg-gray-900
  text: text-gray-100

license:
  title_of_work: 냉전아시아영상아카이브
  link_to_work: https://ccwps.org
  creator_of_work: 팀두루미
  link_to_creator_profile: https://github.com/team-durumi
  year_of_creation: 2022

footer:
  logo: 
  대표전화 : 02-0000-0000
  팩스 : 02-0000-0000
  주소 : (08359) 서울시 구로구 연동로 320 성공회대학교 새천년관 지하1층
  이메일 : kangsh@skhu.ac.kr
  냉전평화연구센터장 : 강성현 (연구소 HK교수, 열림교양대학 교수)
  연구부장 : 전갑생 (연구소 선임연구원)
  year : "2022"
  url : http://ieas21.or.kr/
  caption: 동아시아연구소
  youtube : https://www.youtube.com/playlist?list=PLCNJCqoVaS60YcZyApHq9vXsNEi859VLD
  fb : 
  tw : 
  instagram : 
  linkedin : 

assets:
  alpinejs:
  - core: https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js

googleFonts:
  notosanskr: https://fonts.googleapis.com/css2?family=Noto+Serif+KR:wght@100;400;700&display=swap
